customer1=input("enter the name of the first customer: ")
prix=float(input("enter the price: "))
TTC1=prix*(1+(15/100)-(2/100))
customer2=input("enter the name of the thesecond customer: ")
prix=float(input("enter the price: "))
TTC2=prix*(1+(15/100)-(2/100))
customer3=input("enter the name of the thethird customer: ")
prix=float(input("enter the price: "))
TTC3=prix*(1+(15/100)-(2/100))
print("total to be paid by the customer",customer1,"is;",TTC1)
print("total to be paid by the customer",customer2,"is;",TTC2)
print("total to be paid by the customer",customer3,"is;",TTC3)